# GitHub Actions workflow
name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - master
      - dev

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ORG_GHCR_PAT }}

    # Build and load the image into the local Docker daemon
    - name: Build and Push Multi-Platform Docker Image
      # run: docker buildx build --platform linux/amd64,linux/arm64 --push -t ghcr.io/${{ github.repository }}/levisdrive:latest .
      run: docker buildx build --push -t ghcr.io/leviscodestudio/levis-drive/levisdrive:latest .

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build  # Ensures testing runs after the image is built
  #   steps:
  #    - name: Log in to GitHub Container Registry
  #      uses: docker/login-action@v2
  #      with:
  #       registry: ghcr.io
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.ORG_GHCR_PAT }}

  #     # Run a simple test
  #    - name: Run simple test
  #      run: docker run --rm ghcr.io/leviscodestudio/levis-drive/levisdrive:latest
